version: '3.5'

services:
  frontpage:
    image: nginx:1.16.1
    volumes:
     - "./html:/usr/share/nginx/html:ro"
    deploy:
      replicas: 1
    labels:
      - "traefik.frontend.rule=Host:www.wpcdas.com,wpcdas.com"
      - "traefik.backend=frontpage"
      - "traefik.enable=true"
      - "traefik.port=80"

networks:
  default:
    external: true
    name: swarmnet
